### ISSUE TITLE
cudnn is where exactly?

### ISSUE THREAD

**Issue by lzamparo** [Kaixhin/dockerfiles#11]
Hi,

I'm using your `cuda-torch` container via [docker hub](https://hub.docker.com/r/kaixhin/cuda-torch/), but see no indication that cudnn is installed (libcudnn.so.\* not found anywhere).  Was this introduced only in a later version?  

Thanks,

**Comment by lzamparo** [comment]
Found it: 

```
root@7d29d18748a0:/torch# cd /
root@7d29d18748a0:/# find . -name *.so | grep cudnn
./usr/lib/x86_64-linux-gnu/libcudnn.so
```

However, this is never exposed either in .profile or .bashrc, or ./install/bin/torch-activate.  Manually trying to load the cudnn module yields the error:

```
th> require 'cudnn'
/root/torch/install/share/lua/5.1/cudnn/ffi.lua:574: libcudnn.so: cannot open shared object file: No such file or directory
/root/torch/install/share/lua/5.1/trepl/init.lua:383: /root/torch/install/share/lua/5.1/cudnn/ffi.lua:577: 'libcudnn.so not found in library path.
Please install CuDNN from https://developer.nvidia.com/cuDNN
Then make sure all the files named as libcudnn.so* are placed in your library load path (for example /usr/local/lib , or manually add a path to LD_LIBRARY_PATH)

stack traceback:
    [C]: in function 'error'
    /root/torch/install/share/lua/5.1/trepl/init.lua:383: in function 'require'
    [string "_RESULT={require 'cudnn'}"]:1: in main chunk
    [C]: in function 'xpcall'
    /root/torch/install/share/lua/5.1/trepl/init.lua:650: in function 'repl'
    /root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:199: in main chunk
    [C]: at 0x00406670
```

Maybe you could supply a `cudnn-activate.sh` script which adds `/usr/lib/x86_64-linux-gnu/l` to LD_LIBRARY_PATH?

**Comment by Kaixhin** [comment]
Might be a combination of https://github.com/Kaixhin/dockerfiles/issues/9 and recent builds failing (due to resource limits on the Docker Hub). I've now rebuilt the [CUDA 7.5 version](https://hub.docker.com/r/kaixhin/cuda-torch/builds/) of `kaixhin/cuda-torch`, so please check it out and let me know if `require 'cudnn'` now works.

**Comment by lzamparo** [comment]
require 'cudnn' still fails, but it seems like that's because of no symlink between libcundnn.so.4 and libcudnn.so.  Torch specifically cannot find `libcudnn.so`:

```
th> require 'cudnn'
/root/torch/install/share/lua/5.1/cudnn/ffi.lua:574: libcudnn.so: cannot open shared object file: No such file or directory
```

Yet libcudnn.so.4 exists, 

```
root@34f3bdbad6de:~/torch# ls -lh /usr/lib/x86_64-linux-gnu/libcud*
lrwxrwxrwx 1 root root  12 Sep 13  2015 /usr/lib/x86_64-linux-gnu/libcuda.so -> libcuda.so.1
lrwxrwxrwx 1 root root  17 Sep 13  2015 /usr/lib/x86_64-linux-gnu/libcuda.so.1 -> libcuda.so.352.39
-rwxr-xr-x 1 root root 14M Sep 13  2015 /usr/lib/x86_64-linux-gnu/libcuda.so.352.39
lrwxrwxrwx 1 root root  17 Nov 19 08:44 /usr/lib/x86_64-linux-gnu/libcudnn.so.4 -> libcudnn.so.4.0.4
-rw-r--r-- 1 root root 59M Nov 19 08:44 /usr/lib/x86_64-linux-gnu/libcudnn.so.4.0.4
```

and is present in LD_LIBRARY_PATH:

```
LD_LIBRARY_PATH=/root/torch/install/lib:/root/torch/install/lib:/usr/local/cuda/lib64:/usr/lib/x86_64-linux-gnu/
```

Adding a symlink in from /usr/lib/x86_64-linux.gnu/libcudnn.so -> /usr/lib/x86_64-linux.gnu/libcudnn.so.4.0.4 seems to work:

```
th> require 'cudnn'
{
  getSharedWorkspace : function: 0x412c69e0
  _Pooling3D : {...}
  VolumetricMaxPooling : {...}
  SpatialCrossEntropyCriterion : {...}
  VolumetricConvolution : {...}
  SpatialAveragePooling : {...}
  Tanh : {...}
  C : userdata: 0x4140a3e0
  functional :
    {
      bias2D_accGradParameters : function: 0x401b4158
      Pooling_updateGradInput : function: 0x4141d7e0
      Pooling_updateOutput : function: 0x41870d70
      Convolution2D_accGradParameters : function: 0x41870c50
      MaxPooling2D_updateGradInput : function: 0x41870de8
      Convolution2D_updateOutput : function: 0x4141d788
      bias2D_updateOutput : function: 0x412c44e8
      AveragePooling2D_updateGradInput : function: 0x4141d818
      AveragePooling2D_updateOutput : function: 0x41870dc8
      MaxPooling2D_updateOutput : function: 0x41870da8
      Convolution2D_updateGradInput : function: 0x412c4598
    }
  LogSoftMax : {...}
  benchmark : false
  SpatialConvolution : {...}
  _Pooling : {...}
  SpatialMaxPooling : {...}
  fastest : false
  toDescriptor : function: 0x415b23d0
  ReLU : {...}
  SpatialCrossMapLRN : {...}
  SoftMax : {...}
  version : 4004
  _Pointwise : {...}
  handle : cdata<struct cudnnContext *[?]>: 0x41692020
  SpatialSoftMax : {...}
  getHandle : function: 0x4140a3f8
  Sigmoid : {...}
  SpatialLogSoftMax : {...}
  VolumetricAveragePooling : {...}
  errcheck : function: 0x4140a468
}
```

But maybe you've already done this in the `latest` build? (I don't see a version tagged 7.5)

**Comment by Kaixhin** [comment]
Sorry for the delay - just got back from holiday and can now test on my machine with CUDA 7.5. Since the Docker Hub doesn't allow multiple tags for non-official images, yes `latest` is `7.5`. `require 'cudnn'` seems to work fine on my machine with the latest (6 days old) version of `kaixhin/cuda-torch:latest`.

I also checked `/usr/lib/x86_64-linux-gnu/` for the library, which makes it look like the one you are using is outdated. I'm getting the same versions of `libcudnn` for each version of CUDA, so that shouldn't be the issue. Folder listing below:

``` sh
root@e86ed484a9c3:~/torch# ls -lh /usr/lib/x86_64-linux-gnu/libcud*
lrwxrwxrwx 1 root root  12 Sep 13  2015 /usr/lib/x86_64-linux-gnu/libcuda.so -> libcuda.so.1
lrwxrwxrwx 1 root root  17 Sep 13  2015 /usr/lib/x86_64-linux-gnu/libcuda.so.1 -> libcuda.so.352.39
-rwxr-xr-x 1 root root 14M Sep 13  2015 /usr/lib/x86_64-linux-gnu/libcuda.so.352.39
lrwxrwxrwx 1 root root  29 Mar 15 14:57 /usr/lib/x86_64-linux-gnu/libcudnn.so -> /etc/alternatives/libcudnn_so
lrwxrwxrwx 1 root root  17 Feb  9 07:47 /usr/lib/x86_64-linux-gnu/libcudnn.so.4 -> libcudnn.so.4.0.7
-rw-r--r-- 1 root root 59M Feb  9 07:47 /usr/lib/x86_64-linux-gnu/libcudnn.so.4.0.7
lrwxrwxrwx 1 root root  32 Mar 15 14:57 /usr/lib/x86_64-linux-gnu/libcudnn_static.a -> /etc/alternatives/libcudnn_stlib
-rw-r--r-- 1 root root 60M Feb  9 07:47 /usr/lib/x86_64-linux-gnu/libcudnn_static_v4.a
```

**Comment by lzamparo** [comment]
No problem.  I'm sure it was an older version, since it was missing the `convert` function.  I've since built my own image as an exercise in Docker, but good to know this issue is solved in your image too.
